### ISSUE TITLE
Design Lab - TODO

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/DesignLab#5]
Design Lab

**関連管理**
https://github.com/youbinoyou/KaraageChannel/issues/10

作業について

**作業：アップロード**
- [ ] 【アップロード】 ver 1.0.0

**作業：Design Lab**
- [x] TODO作成
- [ ] TODO整理
- [ ] はじめに
- [ ] スマホデザイン http://fladdict.net/blog/2017/09/iphonex.html

**参考サイト**
- [ ] https://www.nxworld.net/tips/50-css-heading-styling.html
- [ ] http://www.dataplan.jp/blog/css/406
- [ ] http://www.pressmantech.com/tech/design/2738

**作業：コーディング**
- [ ] コーディング

**作業：管理**
- [ ] 清算管理
- [ ] 権利管理
